excluded: # paths to ignore during linting. Takes precedence over 'included'.
  - Pods
  
line_length:
  - 300 # warning
  - 400 # error  

file_length:
  warning: 500
  error: 1200
  
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  max_length:
    warning: 100
    error: 250
    
 
  excluded: # excluded via string array
    - id
    - URL
    - db
    - GlobalAPIKey
    - app_online
    
disabled_rules:
  - trailing_whitespace    
